version: '3.8'

services:
  postgres:
    container_name: stock
    image: bitnami/postgresql:13.16.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres