global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus-docker'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['172.17.0.1:15692']
    metrics_path: '/metrics'
    scheme: 'http'